diseases = [
    "--Select--",
    "Hypertension (High Blood Pressure)",
    "Diabetes Mellitus",
    "Chronic Kidney Disease",
    "Coronary Artery Disease",
    "Chronic Obstructive Pulmonary Disease (COPD)",
    "Asthma",
    "Rheumatoid Arthritis",
    "Osteoarthritis",
    "Alzheimer's Disease",
    "Parkinson's Disease",
    "Multiple Sclerosis",
    "HIV/AIDS",
    "Liver Cirrhosis",
    "Chronic Hepatitis",
    "Breast Cancer",
    "Lung Cancer",
    "Colorectal Cancer",
    "Prostate Cancer",
    "Skin Cancer (Melanoma)",
    "Ovarian Cancer",
    "Pancreatic Cancer",
    "Leukemia",
    "Lymphoma (Hodgkin's and Non-Hodgkin's)",
    "Brain Tumor",
    "Liver Cancer",
    "Kidney Cancer",
    "Bladder Cancer",
    "Esophageal Cancer",
    "Stomach Cancer",
    "Cervical Cancer",
    "Testicular Cancer",
    "Thyroid Cancer",
    "Bone Cancer",
    "Soft Tissue Sarcoma"
]